CREATE DATABASE IF NOT EXISTS AlbumApp;
USE AlbumApp;

DROP TABLE IF EXISTS Albums;

CREATE TABLE Albums(
	Id INT AUTO_INCREMENT,
	Artist VARCHAR(255) NOT NULL,
	Title VARCHAR(255) NOT NULL,
	Year INT NOT NULL,
	Image BLOB NOT NULL,
	CONSTRAINT pk_Albums_Id
		PRIMARY KEY (Id)
);
